[2024-10-17 15:31:02 +0000] [12345] [ERROR] Exception on /translate [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/path/to/translation_api/app.py", line 30, in translate_text
    input_text = data['text']
TypeError: 'NoneType' object is not subscriptable

[2024-10-17 15:32:15 +0000] [12345] [ERROR] 404 Not Found: The requested URL was not found on the server.
